version: '3.8'

services:
  db:
    container_name: taskmanager_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: task
      POSTGRES_PASSWORD: manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
